# config.toml — central config for Lambda runs

# ===== Remote instance =====
[remote]
user = "ubuntu"
host = "192.222.52.92"  # <-- change this when the IP changes
port = 22
ssh_key = "~/.ssh/LambdaSSHkey.pem"

# ===== Project paths =====
[paths]
remote_dir = "/home/ubuntu/NatsFS/cosmos-transfer1"
local_prompts_dir = "./inputs/prompts"
local_runs_dir = "./inputs/runs"
local_videos_dir = "./inputs/videos"
local_outputs_dir = "./outputs"
local_notes_dir = "./notes"

# ===== Docker image on remote =====
[docker]
image = "nvcr.io/ubuntu/cosmos-transfer1:latest"

# ===== Environment variable overrides =====
# These can be set via environment variables to override the defaults above
# Example: export REMOTE_HOST="192.168.1.100" to override the host
